[project]
name = "lsst-cmservice-client-cli"
dynamic = ["version"]
requires-python = ">=3.12,<3.13"
dependencies = [
    "click==8.1.*",
    "lsst-cmservice-core",
    "tabulate==0.9.*",
]

[dependency-groups]

[project.scripts]
cm-client = "lsst.cmservice.client.cli.client:client_top"

[tool.uv]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
ignore-vcs = true

[tool.hatch.build.targets.wheel]
ignore-vcs = true
packages = ["src/lsst"]

[tool.hatch.version]
path = "src/lsst/cmservice/client/__init__.py"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
python_files = ["tests/*.py"]
addopts = "--cov=lsst.cmservice.client --cov-branch --cov-report=term --cov-report=html"
