from __future__ import annotations

import types
from typing import TYPE_CHECKING, Any, ClassVar

from lsst.utils import doImport
from lsst.utils.introspection import get_full_type_name

from ..common.enums import StatusEnum
from ..common.errors import CMBadHandlerTypeError
from ..common.logging import LOGGER

if TYPE_CHECKING:
    from ..common.types import AnyAsyncSession
    from .element import ElementMixin
    from .node import NodeMixin
    from .script import Script

logger = LOGGER.bind(module=__name__)


class Handler:
    """Base class to handle callbacks generated by particular
    database actions.

    Each entry in the database will have an associated
    Handler and specification fragment, which will be used
    where particular database actions are taken.
    """

    handler_cache: ClassVar[dict[int, Handler]] = {}

    def __init__(self, spec_block_id: int, **kwargs: dict) -> None:
        self._spec_block_id = spec_block_id
        self._data = kwargs.copy()

    @classmethod
    def reset_cache(cls) -> None:
        cls.handler_cache = {}

    @classmethod
    def remove_from_cache(
        cls,
        spec_block_id: int,
    ) -> None:
        cls.handler_cache.pop(spec_block_id, None)

    @staticmethod
    def get_handler(
        spec_block_id: int,
        class_name: str,
        **kwargs: dict,
    ) -> Handler:
        """Create and return a handler

        Parameters
        ----------
        spec_block_id: int
            Id for the associated SpecBlock

        class_name : str
            Name of the handler class requested

        Returns
        -------
        handler : Handler
            Requested handler

        Notes
        -----
        The handlers are cached by spec_block_id
        If a cached handler is found that will be returned
        instead of producing a new one.
        """
        cached_handler = Handler.handler_cache.get(spec_block_id)
        if cached_handler is None:
            handler_class = doImport(class_name)
            if isinstance(handler_class, types.ModuleType):  # pragma: no cover
                msg = f"{type(handler_class)} is a Module, not a handler class"
                raise CMBadHandlerTypeError(msg)
            cached_handler = handler_class(spec_block_id, **kwargs)
            Handler.handler_cache[spec_block_id] = cached_handler
        return cached_handler

    @property
    def data(self) -> dict[str, Any]:
        """Return the handler's data"""
        return self._data

    def get_handler_class_name(self) -> str:
        """Return this class's full name"""
        return get_full_type_name(self)

    async def process(
        self,
        session: AnyAsyncSession,
        node: NodeMixin,
        **kwargs: Any,
    ) -> tuple[bool, StatusEnum]:
        """Process a `Node` as much as possible

        Parameters
        ----------
        session : A
            DB session manager

        node: NodeMixin
            The `Node` in question

        kwargs: Any
            Used to override processing configuration

        Returns
        -------
        changed : bool
            True if anything has changed
        status : StatusEnum
            Status of the processing
        """
        msg = f"{type(self)}.process"
        raise NotImplementedError(msg)

    async def run_check(
        self,
        session: AnyAsyncSession,
        node: NodeMixin,
        **kwargs: Any,
    ) -> tuple[bool, StatusEnum]:
        """Check on a Nodes's status

        Parameters
        ----------
        session : A
            DB session manager

        node: NodeMixin
            The `Node` in question

        kwargs: Any
            Used to override processing configuration

        Returns
        -------
        changed : bool
            True if anything has changed
        status : StatusEnum
            Status of the processing
        """
        msg = f"{type(self)}.run_check"
        raise NotImplementedError(msg)

    async def reset(
        self,
        session: AnyAsyncSession,
        node: NodeMixin,
        to_status: StatusEnum,
        *,
        fake_reset: bool = False,
    ) -> StatusEnum:
        """Reset a `Node` to an earlier status

        Parameters
        ----------
        session : A
            DB session manager

        node: NodeMixin
            The `Node` in question

        to_status: StatusEnum
            Status to reset the node to

        fake_reset: bool
            Don't actually try to remove collections if True

        Returns
        -------
        status : StatusEnum
            Status of the processing
        """
        msg = f"{type(self)}.reset"
        raise NotImplementedError(msg)

    async def reset_script(
        self,
        session: AnyAsyncSession,
        node: NodeMixin,
        to_status: StatusEnum,
        *,
        fake_reset: bool = False,
    ) -> StatusEnum:
        """Reset a `Node` to an earlier status

        Parameters
        ----------
        session : A
            DB session manager

        node: NodeMixin
            The `Node` in question

        to_status: StatusEnum
            Status to reset the node to

        fake_reset: bool
            Don't actually try to remove collections if True

        Returns
        -------
        status : StatusEnum
            Status of the processing
        """
        msg = f"{type(self)}.reset_script"
        raise NotImplementedError(msg)

    async def review(
        self,
        session: AnyAsyncSession,
        element: ElementMixin,
        **kwargs: Any,
    ) -> StatusEnum:
        """Review an `Element`

        Parameters
        ----------
        session : A
            DB session manager

        element: ElementMixin
            The `Element` in question

        Returns
        -------
        status : StatusEnum
            Status of the processing
        """
        msg = f"{type(self)}.review"
        raise NotImplementedError(msg)

    async def review_script(
        self,
        session: AnyAsyncSession,
        script: Script,
        parent: ElementMixin,
        **kwargs: Any,
    ) -> StatusEnum:
        """Review a `Script`

        Parameters
        ----------
        session : A
            DB session manager

        script: Script
            The `Script` in question

        parent: ElementMixin
            Parent `Node` from script

        Returns
        -------
        status : StatusEnum
            Status of the processing
        """
        msg = f"{type(self)}.review_script"
        raise NotImplementedError(msg)
