[project]
name = "lsst-cmservice-core"
dynamic = ["version"]
requires-python = ">=3.12,<3.13"
dependencies = [
    "alembic==1.16.*",
    "anyio==4.7.*",
    "asyncpg==0.30.*",
    "fastapi==0.115.*",
    "greenlet==3.1.*",
    "htcondor==24.0.*; sys_platform == 'linux'",
    "jinja2==3.1.*",
    "lsst-ctrl-bps>=29.2025.3400",
    "lsst-ctrl-bps-htcondor>=29.2025.2400; sys_platform == 'linux'",
    "lsst-ctrl-bps-panda>=29.2025.3400",
    "lsst-daf-butler>=29.2025.3400",
    "lsst-pipe-base>=29.2025.3400",
    "lsst-utils>=29.2025.3400",
    "numpy==2.1.*",
    "psycopg2-binary==2.9.*",
    "pydantic==2.11.*",
    "pydantic-settings==2.9.*",
    "python-multipart==0.0.*",
    "structlog==24.4.*",
    "sqlalchemy[asyncio]==2.0.*",
    "safir[db]==7.0.*",
    "uvicorn[standard]==0.34.*",
    "panda-client>=1.5.82",
    "httpx>=0.27.2",
    "networkx>=3.5",
    "sqlmodel>=0.0.24",
    "pytransitions==0.9.*",
    "deepdiff==8.5.*",
]

[dependency-groups]

[tool.uv]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
ignore-vcs = true

[tool.hatch.build.targets.wheel]
ignore-vcs = true
packages = ["src/lsst"]

[tool.hatch.version]
path = "src/lsst/cmservice/core/__init__.py"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
python_files = ["tests/*.py"]
addopts = "--cov=lsst.cmservice.core --cov-branch --cov-report=term --cov-report=html"
