apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cm-pg
spec:
  instances: 1
  bootstrap:
    initdb:
      database: cm-service
      owner: cm-service
      secret:
        name: cm-pg-app
  storage:
    size: 1Gi
