apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-redis
spec:
  selector:
    matchLabels:
      app: cm-redis
  template:
    metadata:
      labels:
        app: cm-redis
    spec:
      containers:
      - name: cm-redis
        image: redis:latest
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cm-redis-app
              key: password
        command: [redis-server, --requirepass, $(REDIS_PASSWORD)]
        ports:
        - containerPort: 6379
        resources:
