version: 2
updates:
  # - package-ecosystem: "uv"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  - package-ecosystem: "bun"
    directory: "/packages/cm-canvas"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    pull-request-branch-name:
      prefix: "u/dependabot"
    groups:
      canvas:
        patterns:
          - "*"
    allow:
      - dependency-type: direct
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      prefix: "u/dependabot"
    groups:
      prek:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      prefix: "u/dependabot"
    groups:
      gha:
        patterns:
          - "*"
