secretGenerator:
- name: cm-pg-app
  namespace: cm-service
  type: kubernetes.io/basic-auth
  files:
  - .secrets/pg/username
  - .secrets/pg/password
generatorOptions:
  disableNameSuffixHash: true
resources:
- ../base
