"""Autogenerated from Model v0.4.0

Revision ID: f5e50e000a35
Revises: fc48b549d66f
Create Date: 2024-12-10 20:47:05.843863+00:00

This migration was auto-generated by `alembic revision --autogenerate` based on
the state of the application model as of tag release v0.4.0, and hand-tuned for
correctness.

Hand tuning consisted of:

- All generated Enums modified with `create_type=False`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5e50e000a35"
down_revision: str | None = "fc48b549d66f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spec_block",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("handler", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("collections", sa.JSON(), nullable=True),
        sa.Column("child_config", sa.JSON(), nullable=True),
        sa.Column("spec_aliases", sa.JSON(), nullable=True),
        sa.Column("scripts", sa.JSON(), nullable=True),
        sa.Column("steps", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("child_config", sa.JSON(), nullable=True),
        sa.Column("collections", sa.JSON(), nullable=True),
        sa.Column("spec_aliases", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "campaign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spec_id", sa.Integer(), nullable=False),
        sa.Column("spec_block_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "failed",
                "rejected",
                "paused",
                "rescuable",
                "waiting",
                "ready",
                "prepared",
                "running",
                "reviewable",
                "accepted",
                "rescued",
                name="statusenum",
                create_type=False,
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column("handler", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("child_config", sa.JSON(), nullable=True),
        sa.Column("collections", sa.JSON(), nullable=True),
        sa.Column("spec_aliases", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["production.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["spec_block_id"], ["spec_block.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["spec_id"], ["specification.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fullname"),
        sa.UniqueConstraint("parent_id", "name"),
    )
    op.create_table(
        "step",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spec_block_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "failed",
                "rejected",
                "paused",
                "rescuable",
                "waiting",
                "ready",
                "prepared",
                "running",
                "reviewable",
                "accepted",
                "rescued",
                name="statusenum",
                create_type=False,
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column("handler", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("child_config", sa.JSON(), nullable=True),
        sa.Column("collections", sa.JSON(), nullable=True),
        sa.Column("spec_aliases", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["campaign.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["spec_block_id"], ["spec_block.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fullname"),
        sa.UniqueConstraint("parent_id", "name"),
    )
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spec_block_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "failed",
                "rejected",
                "paused",
                "rescuable",
                "waiting",
                "ready",
                "prepared",
                "running",
                "reviewable",
                "accepted",
                "rescued",
                name="statusenum",
                create_type=False,
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column("handler", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("child_config", sa.JSON(), nullable=True),
        sa.Column("collections", sa.JSON(), nullable=True),
        sa.Column("spec_aliases", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["step.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["spec_block_id"], ["spec_block.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fullname"),
        sa.UniqueConstraint("parent_id", "name"),
    )
    op.create_table(
        "step_dependency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prereq_id", sa.Integer(), nullable=False),
        sa.Column("depend_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["depend_id"], ["step.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prereq_id"], ["step.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spec_block_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "failed",
                "rejected",
                "paused",
                "rescuable",
                "waiting",
                "ready",
                "prepared",
                "running",
                "reviewable",
                "accepted",
                "rescued",
                name="statusenum",
                create_type=False,
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column("handler", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("child_config", sa.JSON(), nullable=True),
        sa.Column("collections", sa.JSON(), nullable=True),
        sa.Column("spec_aliases", sa.JSON(), nullable=True),
        sa.Column("wms_job_id", sa.String(), nullable=True),
        sa.Column("stamp_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["spec_block_id"], ["spec_block.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fullname"),
    )
    op.create_table(
        "script",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spec_block_id", sa.Integer(), nullable=False),
        sa.Column(
            "parent_level",
            sa.Enum(
                "production",
                "campaign",
                "step",
                "group",
                "job",
                "script",
                "n_levels",
                name="levelenum",
                create_type=False,
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("c_id", sa.Integer(), nullable=True),
        sa.Column("s_id", sa.Integer(), nullable=True),
        sa.Column("g_id", sa.Integer(), nullable=True),
        sa.Column("j_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "failed",
                "rejected",
                "paused",
                "rescuable",
                "waiting",
                "ready",
                "prepared",
                "running",
                "reviewable",
                "accepted",
                "rescued",
                name="statusenum",
                create_type=False,
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum(
                "default",
                "no_script",
                "bash",
                "slurm",
                "htcondor",
                name="scriptmethodenum",
                create_type=False,
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.Column("handler", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("child_config", sa.JSON(), nullable=True),
        sa.Column("collections", sa.JSON(), nullable=True),
        sa.Column("script_url", sa.String(), nullable=True),
        sa.Column("stamp_url", sa.String(), nullable=True),
        sa.Column("log_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["c_id"], ["campaign.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["g_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["j_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["s_id"], ["step.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["spec_block_id"], ["spec_block.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fullname"),
    )
    op.create_table(
        "task_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column("n_expected", sa.Integer(), nullable=False),
        sa.Column("n_done", sa.Integer(), nullable=False),
        sa.Column("n_failed", sa.Integer(), nullable=False),
        sa.Column("n_failed_upstream", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fullname"),
    )
    op.create_table(
        "wms_task_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column("n_unknown", sa.Integer(), nullable=False),
        sa.Column("n_misfit", sa.Integer(), nullable=False),
        sa.Column("n_unready", sa.Integer(), nullable=False),
        sa.Column("n_ready", sa.Integer(), nullable=False),
        sa.Column("n_pending", sa.Integer(), nullable=False),
        sa.Column("n_running", sa.Integer(), nullable=False),
        sa.Column("n_deleted", sa.Integer(), nullable=False),
        sa.Column("n_held", sa.Integer(), nullable=False),
        sa.Column("n_succeeded", sa.Integer(), nullable=False),
        sa.Column("n_failed", sa.Integer(), nullable=False),
        sa.Column("n_pruned", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fullname"),
    )
    op.create_table(
        "product_set",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column("n_expected", sa.Integer(), nullable=False),
        sa.Column("n_done", sa.Integer(), nullable=False),
        sa.Column("n_failed", sa.Integer(), nullable=False),
        sa.Column("n_failed_upstream", sa.Integer(), nullable=False),
        sa.Column("n_missing", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["task_set.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fullname"),
    )
    op.create_table(
        "queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=False),
        sa.Column("time_finished", sa.DateTime(), nullable=True),
        sa.Column("time_next_check", sa.DateTime(), nullable=True),
        sa.Column("interval", sa.Float(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column(
            "node_level",
            sa.Enum(
                "production",
                "campaign",
                "step",
                "group",
                "job",
                "script",
                "n_levels",
                name="levelenum",
                create_type=False,
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("c_id", sa.Integer(), nullable=True),
        sa.Column("s_id", sa.Integer(), nullable=True),
        sa.Column("g_id", sa.Integer(), nullable=True),
        sa.Column("j_id", sa.Integer(), nullable=True),
        sa.Column("script_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["c_id"], ["campaign.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["g_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["j_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["s_id"], ["step.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["script_id"], ["script.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "script_dependency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prereq_id", sa.Integer(), nullable=False),
        sa.Column("depend_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["depend_id"], ["script.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prereq_id"], ["script.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "script_error",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("script_id", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "cmservice",
                "local_script",
                "manifest",
                name="errorsourceenum",
                create_type=False,
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("diagnostic_message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["script_id"], ["script.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("script_error")
    op.drop_table("script_dependency")
    op.drop_table("queue")
    op.drop_table("product_set")
    op.drop_table("wms_task_report")
    op.drop_table("task_set")
    op.drop_table("script")
    op.drop_table("job")
    op.drop_table("step_dependency")
    op.drop_table("group")
    op.drop_table("step")
    op.drop_table("campaign")
    op.drop_table("specification")
    op.drop_table("spec_block")
    op.drop_table("production")
    # ### end Alembic commands ###
