# Start from Rubin Alma9 base image
FROM ghcr.io/lsst-dm/docker-scipipe:9-latest AS base-image

# Create and become lsstsvc1 user
COPY docker/scripts/create-lsstsvc1-user.sh /
RUN /create-lsstsvc1-user.sh && rm /create-lsstsvc1-user.sh
USER lsstsvc1
WORKDIR /home/lsstsvc1

# Install partial Rubin stack
COPY docker/scripts/install-worker-stack.sh .
RUN ./install-worker-stack.sh && rm ./install-worker-stack.sh

#==============================================================================

FROM base-image AS build-image

# Install worker
COPY --chown=lsstsvc1:gu . ./workdir
RUN ./workdir/docker/scripts/install-worker.sh

#==============================================================================

FROM base-image AS runtime-image

# Copy the worker virtual environment
COPY --from=build-image /home/lsstsvc1/venv /home/lsstsvc1/venv
ENV PATH="/home/lsstsvc1/venv/bin:$PATH"

# Make sure worker output won't go into the layer store
VOLUME /output

# Run the worker
COPY docker/scripts/start-worker.sh /
CMD ["/start-worker.sh"]
