# Start with a light linux distro with python 3.11
FROM python:3.11.9-slim-bookworm AS base-image

# Install base packages
COPY docker/scripts/install-fe-base.sh /
RUN /install-fe-base.sh && rm /install-fe-base.sh

#==============================================================================

FROM base-image AS build-image

# Install frontend
COPY . /workdir
RUN /workdir/docker/scripts/install-fe.sh

#==============================================================================

FROM base-image AS runtime-image

# Create and switch to lsstsvc1 user
COPY docker/scripts/create-lsstsvc1-user.sh /
RUN /create-lsstsvc1-user.sh && rm /create-lsstsvc1-user.sh
USER lsstsvc1

# Copy the frontend virtual environment
COPY --from=build-image /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Copy the frontend configs
COPY examples /examples
ENV CM_CONFIGS=/examples

# Make sure frontend output won't go into the layer store
VOLUME /output

# Expose the frontend port
EXPOSE 8080

# Run the frontend
COPY docker/scripts/start-frontend.sh /
CMD ["/start-frontend.sh"]
