# syntax=docker/dockerfile:1

ARG PYTHON_VERSION=3.11
ARG UV_VERSION=0.5

#==============================================================================
# UV SOURCE IMAGE
FROM ghcr.io/astral-sh/uv:${UV_VERSION} AS uv


#==============================================================================
# BASE IMAGE
FROM python:${PYTHON_VERSION}-slim-bookworm AS base-image

# Install base packages
COPY docker/scripts/install-fe-base.sh /
RUN /install-fe-base.sh && rm /install-fe-base.sh


#==============================================================================
# BUILDER IMAGE
FROM base-image AS build-image

# Install and Configure UV
COPY --from=uv /uv /bin/uv
ENV UV_PYTHON_PREFERENCE=system
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV UV_FROZEN=1
ENV UV_LINK_MODE=copy

# Install frontend
WORKDIR /workdir
COPY . .
RUN ./docker/scripts/install-fe.sh

RUN --mount=type=cache,target=/root/.cache/uv <<ENDRUN
    set -e
    /bin/uv sync --no-group dev --no-install-project --no-editable
ENDRUN

#==============================================================================
# RUNTIME IMAGE

FROM base-image AS runtime-image

# Expose the frontend port
EXPOSE 8080

# Make sure frontend output won't go into the layer store
VOLUME /output

# Create and switch to lsstsvc1 user
COPY docker/scripts/create-lsstsvc1-user.sh /
RUN /create-lsstsvc1-user.sh && rm /create-lsstsvc1-user.sh
USER lsstsvc1

# Copy the frontend virtual environment
COPY --from=build-image /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /opt/app

# Copy the application and examples
ENV CM_CONFIGS=/opt/app/examples
COPY examples ./examples
COPY src/lsst ./lsst

# Run the frontend
COPY --chmod=755 <<EOF ./docker-entrypoint.sh
#!/bin/bash
set -euo pipefail

python -Wignore -m lsst.cmservice.cli.commands init
uvicorn lsst.cmservice.main:app --host 0.0.0.0 --port 8080
EOF

CMD ["/opt/app/docker-entrypoint.sh"]
