[project]
name = "lsst-cmservice-api"
dynamic = ["version"]
requires-python = ">=3.12,<3.13"
dependencies = [
    "lsst-cmservice-core",
]

[dependency-groups]

[tool.uv]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
ignore-vcs = true

[tool.hatch.build.targets.wheel]
ignore-vcs = true
packages = ["src/lsst"]

[tool.hatch.version]
path = "src/lsst/cmservice/api/__init__.py"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
python_files = ["tests/*.py"]
addopts = "--cov=lsst.cmservice.api --cov-branch --cov-report=term --cov-report=html"
