- Imports:
      - "${CM_CONFIGS}/example_standard_scripts.yaml"
      - "${CM_CONFIGS}/example_standard_elements.yaml"
      - "${CM_CONFIGS}/example_hsc_micro_steps.yaml"
- SpecBlock:
      name: basic_step
      includes: ["step"]
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/HSC/DRP-RC2.yaml#isr"
      child_config:
          spec_block: group
          base_query: "instrument = 'HSC'"
          split_method: split_by_query
          split_dataset: raw
          split_field: exposure
          split_min_groups: 2
- SpecBlock:
      name: campaign
      handler: lsst.cmservice.handlers.element_handler.ElementHandler
      collections:
          root: 'cm/hsc_rc2_micro'
          campaign_source: HSC/raw/RC2
          campaign_input: "{root}/{campaign}/input"
          campaign_output: "{root}/{campaign}"
          campaign_ancillary: "{root}/{campaign}/ancillary"
          campaign_validation: "{root}/{campaign}/validate"
      data:
          butler_repo: '/repo/main'
          prod_area: 'output/archive'
          data_query: "instrument = 'HSC'"
          lsst_version: "${WEEKLY}"
          bps_script_template: bps_panda_script_template
          bps_yaml_template: bps_yaml_template
          manifest_script_template: manifest_script_template
- Specification:
      name: base
      script_templates:
          - ScriptTemplateAssociation: {script_template_name: bps_panda_script_template}
          - ScriptTemplateAssociation: {script_template_name: bps_panda_yaml_template}
          - ScriptTemplateAssociation: {script_template_name: stack_script_template}
      spec_blocks:
          - SpecBlockAssociation: {spec_block_name: chain_create_script}
          - SpecBlockAssociation: {spec_block_name: chain_prepend_script}
          - SpecBlockAssociation: {spec_block_name: chain_collect_jobs_script}
          - SpecBlockAssociation: {spec_block_name: chain_collect_steps_script}
          - SpecBlockAssociation: {spec_block_name: tag_inputs_script}
          - SpecBlockAssociation: {spec_block_name: tag_create_script}
          - SpecBlockAssociation: {spec_block_name: tag_associate_script}
          - SpecBlockAssociation: {spec_block_name: prepare_step_script}
          - SpecBlockAssociation: {spec_block_name: validate_script}
          - SpecBlockAssociation: {spec_block_name: panda_submit_script}
          - SpecBlockAssociation: {spec_block_name: panda_report_script}
          - SpecBlockAssociation: {spec_block_name: manifest_report_script}
          - SpecBlockAssociation: {spec_block_name: manifest_report_load}
          - SpecBlockAssociation: {spec_block_name: run_jobs}
          - SpecBlockAssociation: {spec_block_name: run_groups}
          - SpecBlockAssociation: {spec_block_name: run_steps}
          - SpecBlockAssociation: {spec_block_name: job}
          - SpecBlockAssociation: {spec_block_name: group}
          - SpecBlockAssociation: {spec_block_name: basic_step}
          - SpecBlockAssociation: {spec_block_name: campaign}
