- Imports:
      - "${CM_CONFIGS}/example_standard_scripts.yaml"
      - "${CM_CONFIGS}/example_standard_elements.yaml"
      - "${CM_CONFIGS}/example_hsc_micro_steps.yaml"
- SpecBlock:
      name: basic_step
      includes: ["step"]
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/HSC/DRP-RC2.yaml#isr"
      child_config:
          spec_block: group
          base_query: "instrument = 'HSC'"
          split_method: split_by_query
          split_dataset: raw
          split_field: exposure
          split_min_groups: 2
- SpecBlock:
      name: campaign
      handler: lsst.cmservice.handlers.element_handler.ElementHandler
      collections:
          root: 'cm/hsc_rc2_micro'
          campaign_source: HSC/raw/RC2
          campaign_input: "{root}/{campaign}/input"
          campaign_output: "{root}/{campaign}"
          campaign_ancillary: "{root}/{campaign}/ancillary"
          campaign_validation: "{root}/{campaign}/validate"
      data:
          butler_repo: '/repo/main'
          prod_area: 'output/archive'
          data_query: "instrument = 'HSC'"
          lsst_version: "${WEEKLY}"
          bps_script_template: bps_panda_script_template
          bps_yaml_template: bps_yaml_template
          manifest_script_template: manifest_script_template
- Specification:
      name: base
      spec_blocks:
          - SpecBlockAssociation: {spec_block_name: campaign}
