- ScriptTemplate:
      name: bps_panda_script_template
      file_path: ${CM_CONFIGS}/example_bps_panda_template.yaml
- ScriptTemplate:
      name: bps_yaml_template
      file_path: ${CM_CONFIGS}/example_template.yaml
- ScriptTemplate:
      name: manifest_script_template
      file_path: ${CM_CONFIGS}/example_manifest_template.yaml
- SpecBlock:
      name: chain_create_script
      handler: lsst.cmservice.handlers.scripts.ChainCreateScriptHandler
- SpecBlock:
      name: chain_prepend_script
      handler: lsst.cmservice.handlers.scripts.ChainPrependScriptHandler
- SpecBlock:
      name: chain_collect_jobs_script
      handler: lsst.cmservice.handlers.scripts.ChainCollectScriptHandler
      data:
          collect: jobs
- SpecBlock:
      name: chain_collect_steps_script
      handler: lsst.cmservice.handlers.scripts.ChainCollectScriptHandler
      data:
          collect: steps
- SpecBlock:
      name: tag_inputs_script
      handler: lsst.cmservice.handlers.scripts.TagInputsScriptHandler
- SpecBlock:
      name: tag_create_script
      handler: lsst.cmservice.handlers.scripts.TagCreateScriptHandler
- SpecBlock:
      name: tag_associate_script
      handler: lsst.cmservice.handlers.scripts.TagAssociateScriptHandler
- SpecBlock:
      name: prepare_step_script
      handler: lsst.cmservice.handlers.scripts.PrepareStepScriptHandler
      collections:
          global_inputs: "{campaign_input}"
- SpecBlock:
      name: validate_script
      handler: lsst.cmservice.handlers.scripts.ValidateScriptHandler
- SpecBlock:
      name: panda_script
      handler: lsst.cmservice.handlers.jobs.PandaScriptHandler
- SpecBlock:
      name: panda_report_script
      handler: lsst.cmservice.handlers.jobs.PandaReportHandler
- SpecBlock:
      name: manifest_report_script
      handler: lsst.cmservice.handlers.jobs.ManifestReportScriptHandler
- SpecBlock:
      name: run_jobs
      handler: lsst.cmservice.handlers.elements.RunJobsScriptHandler
- SpecBlock:
      name: run_groups
      handler: lsst.cmservice.handlers.elements.RunGroupsScriptHandler
- SpecBlock:
      name: run_steps
      handler: lsst.cmservice.handlers.elements.RunStepsScriptHandler
- SpecBlock:
      name: job
      handler: lsst.cmservice.handlers.job_handler.JobHandler
      collections:
          job_run: "{root}/{campaign}/{step}/{group}/{job}"
      scripts:
          - Script:
                name: bps
                spec_block: panda_script
                collections:
                    run: "{job_run}"
                    inputs: ["{step_input}", "{campaign_input}", "{campaign_ancillary}"]
          - Script:
                name: bps_report
                spec_block: panda_report_script
                prerequisites: ['bps']
                collections:
                    run: "{job_run}"
                    inputs: ["{step_input}", "{campaign_input}", "{campaign_ancillary}"]
          - Script:
                name: manifest_report
                spec_block: manifest_report_script
                prerequisites: ['bps_report']
                collections:
                    run: "{job_run}"
      data:
          rescue: false
- SpecBlock:
      name: group
      handler: lsst.cmservice.handlers.element_handler.ElementHandler
      collections:
          group_output: "{root}/{campaign}/{step}/{group}"
          group_validation: "{root}/{campaign}/{step}/{group}/validate"
      scripts:
          - Script:
                name: run
                spec_block: run_jobs
      child_config:
          spec_block: job
- SpecBlock:
      name: step
      handler: lsst.cmservice.handlers.element_handler.ElementHandler
      collections:
          step_input: "{root}/{campaign}/{step}/input"
          step_output: "{root}/{campaign}/{step}_ouput"
          step_public_output: "{root}/{campaign}/{step}"
          step_validation: "{root}/{campaign}/{step}/validate"
      scripts:
          - Script:
                name: prepare
                spec_block: prepare_step_script
                collections:
                    output: "{step_input}"
                    inputs: ["{campaign_input}", "{campaign_ancillary}"]
          - Script:
                name: run
                prerequisites: ['prepare']
                spec_block: run_groups
          - Script:
                name: collect_groups
                prerequisites: ['run']
                spec_block: chain_collect_jobs_script
                collections:
                    inputs: []
                    output: "{step_output}"
          - Script:
                name: make_step_public_output
                prerequisites: ['collect_groups']
                spec_block: chain_create_script
                collections:
                    inputs: ["{step_output}", "{campaign_input}", "{campaign_ancillary}"]
                    output: "{step_public_output}"
- SpecBlock:
      name: dc2_step1
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#step1"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: split_by_query
          split_dataset: raw
          split_field: exposure
          split_min_groups: 3
- SpecBlock:
      name: dc2_step2
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#step2"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: no_split
- SpecBlock:
      name: dc2_step3
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#step3"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: split_by_vals
          split_field: tract
          split_vals:
              - 3828
              - 3829
- SpecBlock:
      name: dc2_step4
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#step4"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: split_by_query
          split_dataset: calexp
          split_field: visit
          split_min_groups: 4
- SpecBlock:
      name: dc2_step5
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#step5"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: split_by_vals
          split_field: tract
          split_vals:
              - 3828
              - 3829
- SpecBlock:
      name: dc2_step6
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#step6"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: split_by_query
          split_dataset: calexp
          split_field: visit
          split_min_groups: 4
- SpecBlock:
      name: dc2_step7
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#step7"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: no_split
- SpecBlock:
      name: dc2_step8
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#step8"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: no_split
- SpecBlock:
      name: dc2_faro_visit
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#faro_visit"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: no_split
- SpecBlock:
      name: dc2_faro_matched
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#faro_matched"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: no_split
- SpecBlock:
      name: dc2_faro_tract
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#faro_tract"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
- SpecBlock:
      name: dc2_plots
      includes: ['step']
      data:
          pipeline_yaml: "${DRP_PIPE_DIR}/pipelines/LSSTCam-imSim/DRP-test-med-1.yaml#analysis_coadd_plots"
      child_config:
          spec_block: group
          base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          split_method: no_split
- SpecBlock:
      name: campaign
      handler: lsst.cmservice.handlers.element_handler.ElementHandler
      collections:
          root: 'cm/p1'
          campaign_source: /prod/raw/all
          campaign_input: "{root}/{campaign}/input"
          campaign_output: "{root}/{campaign}"
          campaign_ancillary: "{root}/{campaign}/ancillary"
          campaign_validation: "{root}/{campaign}/validate"
      scripts:
          - Script:
                name: tag_inputs
                spec_block: tag_inputs_script
                collections:
                    input: "{campaign_source}"
                    output: "{campaign_input}"
          - Script:
                name: ancillary
                spec_block: chain_create_script
                collections:
                    inputs:
                        - calib_input
                        - other_calib_input
                    output:
                        - "{campaign_ancillary}"
          - Script:
                name: run
                spec_block: run_steps
                prerequisites: ['tag_inputs', 'ancillary']
          - Script:
                name: collect_steps
                prerequisites: ['run']
                spec_block: chain_collect_steps_script
                collections:
                    inputs: []
                    output: "{campaign_output}"
      child_config:
          step1:
              spec_block: dc2_step1
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          step2:
              spec_block: dc2_step2
              prerequisites: ['step1']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          step3:
              spec_block: dc2_step3
              prerequisites: ['step2']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2'"
          step4:
              spec_block: dc2_step4
              prerequisites: ['step3']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          step5:
              spec_block: dc2_step5
              prerequisites: ['step4']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          step6:
              spec_block: dc2_step6
              prerequisites: ['step4']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          step7:
              spec_block: dc2_step7
              prerequisites: ['step3']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          step8:
              spec_block: dc2_step8
              prerequisites: ['step3']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          faro_visit:
              spec_block: dc2_faro_visit
              prerequisites: ['step6']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          faro_matched:
              spec_block: dc2_faro_matched
              prerequisites: ['step6']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          faro_tract:
              spec_block: dc2_faro_tract
              prerequisites: ['step3']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          plots:
              spec_block: dc2_plots
              prerequisites: ['step3']
              child_config:
                  base_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
      data:
          butler_repo: '/repo/dc2'
          prod_area: 'output/archive'
          data_query: "instrument='LSSTCam-imSim' and skymap='DC2' and tract in (3828, 3829)"
          lsst_version: "${WEEKLY}"
          bps_script_template: bps_panda_script_template
          bps_yaml_template: bps_yaml_template
          manifest_script_template: manifest_script_template
