import json

from deepdiff import DeepDiff, Delta
from httpx import HTTPStatusError, Response, codes
from nicegui import ui

from .client_factory import CLIENT_FACTORY


async def patch_resource(manifest_url: str, t1: dict, t2: dict) -> None:
    """Issues a PATCH to the manifest API using the binary diff of the two
    dictionary parameters.

    The binary diff is generated by the ``deepdiff`` package's ``Delta`` class
    which is understood by the PATCH API as an octet-stream content-type.
    """
    # t2 is the result of a ui.jsoneditor session, which may be either a json
    # string or a python dict
    if "text" in t2:
        t2 = json.loads(t2["text"])
    else:
        t2 = t2["json"]

    diff = DeepDiff(t1, t2)
    delta = Delta(diff)

    async with CLIENT_FACTORY.aclient() as session:
        try:
            r = await session.patch(
                headers={"Content-Type": "application/octet-stream"},
                url=manifest_url,
                content=delta.dumps(),
            )
            r.raise_for_status()
            ui.notify("Update successful", type="positive")
        except HTTPStatusError as e:
            match e.response:
                case Response(status_code=codes.CONFLICT):
                    ui.notify(
                        (
                            "Update failed - Conflict detected - Are you editing "
                            "the most recent version of this element?"
                        ),
                        type="negative",
                    )
                case _:
                    ui.notify(e, type="negative")
