# CI workflow runs linting, typing, and unit tests on every push to a branch
# and when called from another workflow.
---
name: "CI"
"on":
  workflow_call:
  push:
    branches:
      - "tickets/**"
      - "u/**"

env:
  UV_FROZEN: "1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.x"
          enable_cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install packages for testing
        run: uv sync --dev --frozen

      - name: Run tests
        run: |
          uv run playwright install
          uv run make test

  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.x"
          enable_cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install packages for testing
        run: uv sync --dev --frozen

      - name: Run tests
        run: uv run make typing
