name: "CI"
"on":
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages for testing
        run: |
          pip install -r requirements/main.txt -r requirements/dev.txt
          pip install -e .

      - name: Run tests
        run: |
          make test

  mypy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install packages for testing
        run: |
          pip install -r requirements/main.txt -r requirements/dev.txt
          pip install -e .

      - name: Run tests
        run: |
          make typing
