# CI workflow runs linting, typing, and unit tests on every push to a branch
# and when called from another workflow.
---
name: "CI"

"on":
  workflow_call:
  push:
    branches:
      - "tickets/**"
      - "u/**"

env:
  UV_FROZEN: "1"

jobs:
  rebase-checker:
    uses:
      ./.github/workflows/rebase_checker.yaml

  lint:
    runs-on: ubuntu-latest
    needs:
      - rebase-checker
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    needs:
      - rebase-checker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.x"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install packages for testing
        run: uv sync --dev --frozen

      - name: Run tests
        run: uv run make typing

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    needs:
      - lint
      - mypy
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.x"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install packages for testing
        run: uv sync --dev --frozen

      - name: Run tests
        run: |
          uv run playwright install
          uv run make test


  build-and-push:
    needs:
      - test
    if: ${{ startsWith(github.ref_name, 'tickets/DM-') }}
    uses: ./.github/workflows/build_and_push.yaml
