# CI workflow runs linting, typing, and unit tests on every push to a branch
# and when called from another workflow.
---
name: "CI"

"on":
  workflow_call:
  push:
    branches:
      - "tickets/**"
      - "u/**"

env:
  UV_VERSION: "0.11.x"
  UV_FROZEN: "1"
  TEST__LOCAL_DB: "1"  # signals test fixtures to not use testcontainers

jobs:
  rebase-checker:
    uses:
      ./.github/workflows/rebase_checker.yaml
    with:
      rebase-checker: true
      check-conventional: true
      custom-rules: './.github/commitlint.ts'

  lint:
    runs-on: ubuntu-latest
    needs:
      - rebase-checker
    steps:

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.13"

      - name: Run prek
        uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d  # v2.0.4

  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    needs:
      - rebase-checker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install packages for testing
        run: uv sync --dev --frozen --all-extras

      - name: Run tests
        run: uv run make typing

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    needs:
      - lint
      - mypy
    steps:

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install packages for testing
        run: uv sync --dev --all-packages --frozen

      - name: Run tests
        run: |
          uv run playwright install
          uv run make test


  build-and-push:
    needs:
      - test
    if: ${{ startsWith(github.ref_name, 'tickets/DM-') }}
    uses: ./.github/workflows/build_and_push.yaml
    secrets: inherit
