---
name: Commitlint

"on":
  workflow_call:
    inputs:
      check-conventional:
        description: 'Check conventional commits'
        required: false
        type: boolean
        default: true
      custom-rules:
        description: >-
          Custom rules module to use with check-conventional, may be a `ts` or
          `mjs` file but cannot import other files.
          (relative path to file, e.g., `./path/to/config.ts`)
        required: false
        type: string
        default: ""

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - name: Determine commit range
        id: commits
        run: |
          if [[ '${{ github.event_name }}' == "pull_request" ]]; then
            HEAD='${{ github.event.pull_request.head.sha }}'
            BASE='${{ github.event.pull_request.base.sha }}'
          elif [[ '${{ github.event_name }}' == "push" ]]; then
            MAIN='origin/${{ github.event.repository.default_branch }}'
            BRANCH='${{ github.ref_name }}'
            HEAD='${{ github.event.after }}'
            BASE="$(git log $MAIN..$BRANCH --oneline --format=%H | tail -1)"
          fi
          echo "base=${BASE}" >> $GITHUB_OUTPUT
          echo "head=${HEAD}" >> $GITHUB_OUTPUT

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6  # v2.2.0
        with:
          bun-version: latest

      - name: Create bun lockfile (not run)
        if: false
        working-directory: .github/commitlint
        run: |
          bun add --minimum-release-age=604800 --production --lockfile-only \
          '@commitlint/cli@21.2.0' \
          '@commitlint/config-conventional@21.2.0' \
          'conventional-commits-parser@6.4.0'

      - name: Install commitlint
        working-directory: .github/commitlint
        run: >
          bun install --frozen-lockfile --no-save

      - name: Validate Commits as Conventional Commits
        if: inputs.check-conventional
        working-directory: .github/commitlint
        run: |
          CUSTOM_RULES="${{ inputs.custom-rules }}"
          if [[ -n "${CUSTOM_RULES}" ]]
          then
            ext="${CUSTOM_RULES##*.}"
            cp "${GITHUB_WORKSPACE}/${CUSTOM_RULES}" "./custom-rules.${ext}"
            CONFIG_EXTENDS="--extends ./custom-rules.${ext}"
          else
            CONFIG_EXTENDS="--default-config"
          fi

          bunx --no-install --bun commitlint ${CONFIG_EXTENDS} \
          --from '${{ steps.commits.outputs.base }}' --to '${{ steps.commits.outputs.head }}' \
          --verbose
