# Default Seeds for CM V2 Library Manifests
# Library Manifests reside in the default namespace and are always version 0
---
apiVersion: io.lsst.cmservice/v1
kind: lsst
metadata:
  name: slac_w_latest_dev
  namespace: dda54a0c-6878-5c95-ac4f-007f6808049e
  version: 0
  labels:
    site: slac
    environment: dev
    track: weekly
spec:
  artifact_path: /sdf/group/rubin/shared/campaigns/users/usdf-cm-dev
  lsst_version: w_latest
  lsst_distrib_dir: /sdf/group/rubin/sw/w_latest
# ---
# apiVersion: io.lsst.cmservice/v1
# kind: lsst
# metadata:
#   name: usdf_w_latest
#   namespace: dda54a0c-6878-5c95-ac4f-007f6808049e
#   version: 0
#   labels:
#     site: usdf
#     environment: prod
#     track: weekly
# spec:
#   artifact_path: /sdf/group/rubin/shared/campaigns/users/usdf-cm
#   lsst_version: w_latest
#   lsst_distrib_dir: /sdf/group/rubin/sw/w_latest
---
apiVersion: io.lsst.cmservice/v1
kind: butler
metadata:
  name: repo_main_lsstcam_defaults
  namespace: dda54a0c-6878-5c95-ac4f-007f6808049e
  version: 0
  labels:
    site: slac
    instrument: lsstcam
    embargo: "false"
spec:
  repo: "/repo/main"
  predicates:
    - instrument='LSSTCam'
    - skymap='lsst_cells_v2'
  collections:
    campaign_input:
      - LSSTCam/defaults
---
apiVersion: io.lsst.cmservice/v1
kind: wms
metadata:
  name: slac_htcondor
  namespace: dda54a0c-6878-5c95-ac4f-007f6808049e
  version: 0
  labels:
    wms: htcondor
    site: slac
spec:
  batch_system: "htcondor"
  service_class: "lsst.ctrl.bps.htcondor.HTCondorService"
  batch_name: "usdf-cm-dev"
  request_cpus: "1"
  request_mem: "1024M"
  request_disk: "10240K"
  auto_provision: false
  provisioned_node_count: 10
  provisioned_max_wall_time: "0-1:0:0"
  provisioned_idle_time: 900
  provisioned_check_interval: 600
# ---
# apiVersion: io.lsst.cmservice/v1
# kind: wms
# metadata:
#   name: slac_panda
#   namespace: dda54a0c-6878-5c95-ac4f-007f6808049e
#   version: 0
#   labels:
#     wms: panda
#     site: slac
# spec:
#   batch_system: "panda"
#   service_class: "lsst.ctrl.bps.panda.PanDAService"
# environment:
#   IDDS_MAX_NAME_LENGTH: "30000"
#   PANDA_SYS: "${CONDA_PREFIX}"
#   IDDS_CONFIG: "${PANDA_SYS}/etc/idds/idds.cfg.client.template"
#   BPS_WMS_SERVICE_CLASS: "lsst.ctrl.bps.panda.PanDAService"
# custom_setup:
#   - ["unset", "PANDA_CONFIG_ROOT"]
---
apiVersion: io.lsst.cmservice/v1
kind: site
metadata:
  name: slac_lsstcam
  namespace: dda54a0c-6878-5c95-ac4f-007f6808049e
  version: 0
  labels:
    site: slac
    instrument: lsstcam
spec:
  facility: "SLAC"
  include_files:
    - "${DRP_PIPE_DIR}/bps/caching/LSSTCam/usdf/DRP-caching.yaml"
  provisioned_platform: "s3df"
  provisioned_queue: "milano"
  provisioned_account_group: "rubin:developers"
---
apiVersion: io.lsst.cmservice/v1
kind: bps
metadata:
  name: bps_slac
  namespace: dda54a0c-6878-5c95-ac4f-007f6808049e
  version: 0
  labels:
    site: slac
spec:
  operator: lsstsvc1
